Repository AndLetgo/2nd-Main-JeonsiLog-Client, pull requests merged in 2024-01, with the labels that each got.

#38 [PR] develop <- ISSUE-27-feat/#35-API-MyPage
  JeonsiLog/app/src/main/AndroidManifest.xml
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/TokenRefreshInterceptor.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/api/FollowApi.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/api/S3Api.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/api/UserApi.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/follow/GetMyFollowingResponse.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/follow/GetOtherFollowingResponse.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/interest/GetInterestResponse.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/follow/FollowRepository.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/follow/FollowRepositoryImpl.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/s3/S3Repository.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/s3/S3RepositoryImpl.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/user/UserRepository.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/user/UserRepositoryImpl.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/MainActivity.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageInterestFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageListFollowerFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageListFollowingFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageListFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageListRvAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageRatingFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageReviewFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageRvAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageSettingFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/spalshpage/SplashActivity.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/viewmodel/MyPageViewModel.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/widget/utils/GlobalApplication.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/widget/utils/ImageUtil.kt
  JeonsiLog/app/src/main/res/layout/item_my_page_interest.xml
  JeonsiLog/app/src/main/res/layout/item_my_page_rating.xml
  JeonsiLog/app/src/main/res/layout/item_my_page_review.xml
Labels: feature

#40 [PR] develop <- ISSUE-31-feat/#39-API#2
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/api/CalendarApi.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/api/ReplyApi.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/api/ReportApi.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/calendar/GetMyPhotoResponse.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/calendar/PostPhotoFromGalleryRequest.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/calendar/PostPhotoFromPosterRequest.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/reply/GetReplyResponse.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/reply/PostReplyRequest.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/reply/PostReportRequest.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/report/GetReportsResponse.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/calendar/CalendarRepository.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/calendar/CalendarRepositoryImpl.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/reply/ReplyRepository.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/reply/ReplyRepositoryImpl.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/report/ReportRepository.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/report/ReportRepositoryImpl.kt
Labels: feature

#42 [PR] develop <- ISSUE-29-feat/#37-API-HomePage
  JeonsiLog/app/src/main/AndroidManifest.xml
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/api/ExhibitionApi.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/exhibition/ExhibitionRepository.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/MainActivity.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ExhibitionFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ExtraActivity.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/home/HomeFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/home/HomeRvAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/spalshpage/SplashActivity.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/viewmodel/HomeViewModel.kt
  JeonsiLog/app/src/main/res/drawable/btn_home_fab.xml
  JeonsiLog/app/src/main/res/drawable/ic_bn_photocalendar_inactive_24.xml
  JeonsiLog/app/src/main/res/layout/activity_main.xml
  JeonsiLog/app/src/main/res/layout/fragment_home.xml
  JeonsiLog/app/src/main/res/layout/item_home_exhibition.xml
  JeonsiLog/app/src/main/res/values/dimens.xml
  JeonsiLog/app/src/main/res/values/strings.xml
  JeonsiLog/app/src/main/res/values/themes.xml
Labels: feature

#46 [PR] develop <- ISSUE-30-feat/#43-API-ExhibitionPage
  JeonsiLog/app/build.gradle
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/api/PlaceApi.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/reply/GetReplyResponse.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/place/PlaceRepository.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ExhibitionFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ExhibitionPlaceFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ExhibitionPlaceRvAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ExhibitionReplyRvAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ExhibitionReviewRvAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ExtraActivity.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/PosterFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/PosterVpAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ReviewFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/home/HomeFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/home/HomeRvAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/photocalendar/LoadPageRvAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/ExhibitionInfoItemAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/ExhibitionPlaceItemAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/viewmodel/ExhibitionViewModel.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/viewmodel/ReviewViewModel.kt
  JeonsiLog/app/src/main/res/layout/fragment_exhibition.xml
  JeonsiLog/app/src/main/res/layout/fragment_exhibition_place.xml
  JeonsiLog/app/src/main/res/layout/fragment_review.xml
  JeonsiLog/app/src/main/res/layout/item_exhibition_place.xml
  JeonsiLog/app/src/main/res/layout/item_exhibition_review.xml
  JeonsiLog/app/src/main/res/navigation/nav_exhibition.xml
  JeonsiLog/app/src/main/res/values/strings.xml
Labels: feature

#47 [PR] develop <- ISSUE-33-mod/#45-MOD-SignUpPage
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/TokenRefreshInterceptor.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/login/SignUpActivity.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageNickEditDialog.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/spalshpage/SplashActivity.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/viewmodel/SignUpViewModel.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/widget/utils/GlobalApplication.kt
  JeonsiLog/app/src/main/res/layout/activity_signup.xml
Labels: mod

#50 [PR] develop <- ISSUE-34-feat/#48-ToS
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/login/SignUpActivity.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/login/SignUpFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/login/TosFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/spalshpage/SplashActivity.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/viewmodel/SignUpViewModel.kt
  JeonsiLog/app/src/main/res/layout/activity_signup.xml
  JeonsiLog/app/src/main/res/layout/fragment_signup.xml
  JeonsiLog/app/src/main/res/layout/fragment_tos.xml
  JeonsiLog/app/src/main/res/values/strings.xml
Labels: feature

#53 [PR] develop <- ISSUE-36-mod/#52-DETAIL-Profile
  JeonsiLog/app/build.gradle
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/RetrofitClient.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/MainActivity.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageListRvAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageRvAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageSettingFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserListFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserListRvAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/UserSearchItemAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/viewmodel/OtherUserViewModel.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/widget/utils/SpannableStringUtil.kt
  JeonsiLog/app/src/main/res/layout/fragment_my_page.xml
  JeonsiLog/app/src/main/res/layout/fragment_my_page_list.xml
  JeonsiLog/app/src/main/res/layout/fragment_other_user.xml
  JeonsiLog/app/src/main/res/layout/fragment_other_user_list.xml
  JeonsiLog/app/src/main/res/layout/item_my_page_interest.xml
Labels: fix, mod

#55 [PR] develop <- ISSUE-30-feat/#43-API-ExhibitionPage
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/exhibition/GetExhibitionResponse.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ExhibitionFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ExhibitionPlaceFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ExhibitionPlaceRvAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/PosterFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/WritingReviewFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/home/HomeFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageListRvAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserListFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserListRvAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/UserSearchItemAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/viewmodel/ExhibitionModel.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/viewmodel/ExhibitionWritingViewModel.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/viewmodel/HomeRvModel.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/viewmodel/OtherUserViewModel.kt
  JeonsiLog/app/src/main/res/layout/fragment_exhibition.xml
  JeonsiLog/app/src/main/res/layout/fragment_other_user_list.xml
  JeonsiLog/app/src/main/res/layout/fragment_writing_review.xml
  JeonsiLog/app/src/main/res/values/strings.xml
Labels: feature

#56 ISSUE-38 [mod] SearchPage 뒤로가기 처리
  JeonsiLog/app/build.gradle
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/MainActivity.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/photocalendar/CalendarBottomDialog.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/photocalendar/LoadBottomDialog.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/ExhibitionInfoItemAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/ExhibitionPlaceItemAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/RecordItemAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/RecordSearchFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/SearchFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/SearchResultFrament.kt
  JeonsiLog/app/src/main/res/layout/activity_main.xml
  JeonsiLog/app/src/main/res/layout/fragment_my_page_rating.xml
  JeonsiLog/app/src/main/res/layout/fragment_search_record.xml
  JeonsiLog/app/src/main/res/layout/fragment_search_result.xml
  JeonsiLog/app/src/main/res/layout/view_load_page_dialog.xml
  JeonsiLog/app/src/main/res/values/style.xml
Labels: mod

#58 [PR] develop <- ISSUE-39-mod/#57-MOD-Profile
  JeonsiLog/app/build.gradle
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/RetrofitClient.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/exhibition/GetExhibitionResponse.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/MainActivity.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ExhibitionFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ExhibitionPlaceFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ExhibitionPlaceRvAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/PosterFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/WritingReviewFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/home/HomeFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageListRvAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageRvAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageSettingFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserListFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserListRvAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/photocalendar/CalendarBottomDialog.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/photocalendar/LoadBottomDialog.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/ExhibitionInfoItemAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/ExhibitionPlaceItemAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/RecordItemAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/RecordSearchFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/SearchFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/SearchResultFrament.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/UserSearchItemAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/viewmodel/ExhibitionModel.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/viewmodel/ExhibitionWritingViewModel.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/viewmodel/HomeRvModel.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/viewmodel/OtherUserViewModel.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/widget/utils/SpannableStringUtil.kt
  JeonsiLog/app/src/main/res/layout/activity_main.xml
  JeonsiLog/app/src/main/res/layout/fragment_exhibition.xml
  JeonsiLog/app/src/main/res/layout/fragment_my_page.xml
  JeonsiLog/app/src/main/res/layout/fragment_my_page_interest.xml
  JeonsiLog/app/src/main/res/layout/fragment_my_page_list.xml
  JeonsiLog/app/src/main/res/layout/fragment_my_page_rating.xml
  JeonsiLog/app/src/main/res/layout/fragment_my_page_review.xml
  JeonsiLog/app/src/main/res/layout/fragment_notification.xml
  JeonsiLog/app/src/main/res/layout/fragment_other_user.xml
  JeonsiLog/app/src/main/res/layout/fragment_other_user_list.xml
  JeonsiLog/app/src/main/res/layout/fragment_search_record.xml
  JeonsiLog/app/src/main/res/layout/fragment_search_result.xml
  JeonsiLog/app/src/main/res/layout/fragment_writing_review.xml
  JeonsiLog/app/src/main/res/layout/item_my_page_interest.xml
  JeonsiLog/app/src/main/res/layout/item_my_page_rating.xml
  JeonsiLog/app/src/main/res/layout/view_load_page_dialog.xml
  JeonsiLog/app/src/main/res/values/strings.xml
  JeonsiLog/app/src/main/res/values/style.xml
Labels: feature, fix, mod

#61 [PR] develop <- ISSUE-39-mod/#57-MOD-Profile
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/MainActivity.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageRvAdapter.kt
  JeonsiLog/app/src/main/res/layout/fragment_my_page.xml
  JeonsiLog/app/src/main/res/layout/fragment_my_page_interest.xml
  JeonsiLog/app/src/main/res/layout/fragment_my_page_list.xml
  JeonsiLog/app/src/main/res/layout/fragment_my_page_review.xml
  JeonsiLog/app/src/main/res/layout/fragment_notification.xml
  JeonsiLog/app/src/main/res/layout/fragment_other_user.xml
  JeonsiLog/app/src/main/res/layout/fragment_other_user_list.xml
  JeonsiLog/app/src/main/res/layout/item_my_page_interest.xml
  JeonsiLog/app/src/main/res/layout/item_my_page_rating.xml
Labels: feature, fix, mod

#65 [PR] develop <- ISSUE-41-mod/#63-Detail-SearchPage
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/MainActivity.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/ExhibitionInfoFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/ExhibitionPlaceFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/RecordItemAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/RecordSearchFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/SearchFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/SearchResultFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/UserSearchFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/UserSearchItemAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/viewmodel/SearchViewModel.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/widget/utils/PreferenceUtil.kt
  JeonsiLog/app/src/main/res/drawable/ic_place.xml
  JeonsiLog/app/src/main/res/drawable/illus_default_profile.png
  JeonsiLog/app/src/main/res/layout/fragment_exihibition_info.xml
  JeonsiLog/app/src/main/res/layout/fragment_home.xml
  JeonsiLog/app/src/main/res/layout/fragment_search_exhibition_place.xml
  JeonsiLog/app/src/main/res/layout/fragment_search_record.xml
  JeonsiLog/app/src/main/res/layout/fragment_user_search.xml
  JeonsiLog/app/src/main/res/layout/item_exhibition_info.xml
  JeonsiLog/app/src/main/res/layout/item_exihibition_search.xml
  JeonsiLog/app/src/main/res/layout/item_user_search.xml
Labels: feature, mod

#77 [PR] develop <- ISSUE-46-feat/#76-ForbiddenWordCheck
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/auth/IsAvailableResponse.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/auth/SignUpRequest.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/auth/AuthRepository.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/auth/AuthRepositoryImpl.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/login/SignUpActivity.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/login/SignUpFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageNickEditDialog.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/spalshpage/SplashActivity.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/viewmodel/SignUpViewModel.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/widget/utils/CryptedPreferenceUtil.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/widget/utils/GlobalApplication.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/widget/utils/NickValidChecker.kt
  JeonsiLog/app/src/main/res/drawable/shape_corner_round_duplicate_btn.xml
  JeonsiLog/app/src/main/res/drawable/shape_corner_round_duplicate_btn_activate.xml
  JeonsiLog/app/src/main/res/layout/fragment_my_page.xml
  JeonsiLog/app/src/main/res/layout/fragment_other_user.xml
  JeonsiLog/app/src/main/res/layout/fragment_signup.xml
  JeonsiLog/app/src/main/res/layout/item_my_page_list_follow.xml
  JeonsiLog/app/src/main/res/layout/item_my_page_list_following.xml
  JeonsiLog/app/src/main/res/values/strings.xml
Labels: feature, mod

#78 [PR] develop <- ISSUE-37-feat/#73-API-Notification
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/api/AlarmApi.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/alarm/GetAlarmResponse.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/alarm/AlarmRepository.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/alarm/AlarmRepositoryImpl.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/notification/NotiActivityFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/notification/NotiExhibitionFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/notification/NotiFollowingFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/notification/NotiMyActivityFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/notification/NotiVpAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/notification/NotificationFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/notification/NotificationModel.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/notification/NotificationRvAdapter.kt
  JeonsiLog/app/src/main/res/layout/fragment_noti_activity.xml
  JeonsiLog/app/src/main/res/layout/fragment_noti_exhibition.xml
  JeonsiLog/app/src/main/res/layout/fragment_notification.xml
  JeonsiLog/app/src/main/res/layout/item_noti_activity.xml
  JeonsiLog/app/src/main/res/layout/item_noti_exhibition.xml
Labels: feature

#80 [PR] develop <- ISSUE-47-mod/#79-MOD-OtherUser
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/api/UserApi.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/user/GetIsOpenResponse.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/user/UserRepository.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/user/UserRepositoryImpl.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserCalendarFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/viewmodel/OtherUserCalendarViewModel.kt
Labels: feature, mod

#82 [PR] develop <- ISSUE-48-mod/#81-MOD-Profile
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageInterestFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageInterestModel.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageListFollowerModel.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageListFollowingModel.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageRatingFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageRatingModel.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageReviewFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageReviewModel.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageRvAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserCalendarModel.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserRatingFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserRatingModel.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserReviewFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserReviewModel.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserRvAdapter.kt
Labels: mod

#86 [PR] develop <- ISSUE-50-fix/#85-FIX-Permission
  JeonsiLog/app/src/main/AndroidManifest.xml
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/MainActivity.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/login/SignUpActivity.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/login/SignUpFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageFragment.kt
Labels: feature, fix

#91 [PR] develop <- ISSUE-35feat/#75-DETAIL-HomePage
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/home/HomeFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/home/HomeRvAdapter.kt
  JeonsiLog/app/src/main/res/layout/fragment_home.xml
Labels: feature

#95 [PR] develop <- ISSUE-45-feat/#7-DETAIL-SearchPage-02
  JeonsiLog/app/build.gradle
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/api/UserApi.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/user/UserRepository.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/user/UserRepositoryImpl.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/ExhibitionInfoItemAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/ExhibitionPlaceItemAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/UserSearchFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/UserSearchItemAdapter.kt
  JeonsiLog/app/src/main/res/layout/item_exhibition_info.xml
  JeonsiLog/app/src/main/res/layout/item_home_exhibition.xml
Labels: feature, mod

#99 [PR] develop <- ISSUE-56-mod/#98-MOD-Home
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/home/HomeFragment.kt
Labels: mod

#102 [PR] develop <- ISSUE-58-mod/#101-MOD-Profile
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/follow/GetMyFollowerResponse.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/follow/GetMyFollowingResponse.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/follow/GetOtherFollowerResponse.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/follow/GetOtherFollowingResponse.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/interest/GetInterestResponse.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/rating/GetRatingsResponse.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/review/GetReviewsResponse.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageInterestFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageListFollowerFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageListFollowingFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageListRvAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageRatingFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageReviewFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageRvAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserListFollowerFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserListFollowingFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserListRvAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserRatingFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserReviewFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserRvAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/viewmodel/OtherUserViewModel.kt
Labels: mod

#104 [PR] develop <- ISSUE-57-mod/#100-MOD-Exhibition
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/api/ReviewApi.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/place/GetPlacesResponse.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/reply/GetReplyResponse.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/review/GetReviewsExhibitionResponse.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/review/ReviewRepository.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/review/ReviewRepositoryImpl.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ExhibitionFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ExhibitionPlaceFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ReviewFragment.kt
Labels: mod

#107 [PR] develop <- ISSUE-59-mod/#10-MOD-SearchPage
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/exhibition/SearchResponse.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/place/SearchPlacesResponse.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/user/SearchUserResponse.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/ExhibitionInfoFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/ExhibitionInfoItemAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/ExhibitionPlaceFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/ExhibitionPlaceItemAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/UserSearchFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/UserSearchItemAdapter.kt
Labels: feature, mod

#110 [PR] develop <- ISSUE-61feat/#108-NETWORK-Home&Exhibition
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ExhibitionFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ExhibitionPlaceFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ExtraActivity.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/PosterFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ReviewFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/WritingReviewFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/home/HomeFragment.kt
  JeonsiLog/app/src/main/res/layout/fragment_review.xml
  JeonsiLog/app/src/main/res/layout/item_exhibition_place.xml
  JeonsiLog/app/src/main/res/layout/item_exhibition_review.xml
  JeonsiLog/app/src/main/res/layout/item_review_reply.xml
  JeonsiLog/app/src/main/res/values/strings.xml
Labels: feature

#113 [PR] develop <- ISSUE-62-feat/#111-API-SearPage
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/place/SearchPlacesResponse.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/ExhibitionPlaceItemAdapter.kt
  JeonsiLog/app/src/main/res/layout/item_exihibition_search.xml
Labels: feature

#124 [PR] develop <- ISSUE-69-fix/#123-FIX-Profile
  JeonsiLog/app/build.gradle
  JeonsiLog/app/src/main/java/com/example/jeonsilog/base/BaseActivity.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/follow/GetMyFollowerResponse.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/follow/GetMyFollowingResponse.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/follow/GetOtherFollowerResponse.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/follow/GetOtherFollowingResponse.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageListFollowerFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageListFollowingFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageListRvAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserListRvAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/widget/extension/LodingDialog.kt
  JeonsiLog/app/src/main/res/layout/dialog_loding.xml
Labels: feature, fix

#127 [PR] develop <- ISSUE-71-mod/#126-MOD-NetworkDialog
  JeonsiLog/app/src/main/res/layout/dialog_network.xml
  JeonsiLog/app/src/main/res/layout/item_other_user_rating.xml
Labels: mod

#132 [PR] develop <- ISSUE-65-feat/#116-FCM-services
  JeonsiLog/app/build.gradle
  JeonsiLog/app/src/main/AndroidManifest.xml
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/api/UserApi.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/user/ChangeFcmTokenRequest.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/user/ChangeFcmTokenResponse.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/fcm/services/FcmDialog.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/fcm/services/FirebaseMessagingService.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/user/UserRepository.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/user/UserRepositoryImpl.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/MainActivity.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/notification/NotificationFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/widget/utils/PreferenceUtil.kt
  JeonsiLog/app/src/main/res/drawable/fcm_logo_jeonsilog.png
  JeonsiLog/app/src/main/res/drawable/illus_dialog_fcm.xml
  JeonsiLog/app/src/main/res/drawable/notification_logo.png
  JeonsiLog/app/src/main/res/layout/dialog_fcm.xml
  JeonsiLog/app/src/main/res/values/strings.xml
  JeonsiLog/build.gradle
Labels: feature

#134 [PR] develop <- ISSUE-74-fix/#133-FIX-FCM
  JeonsiLog/app/src/main/java/com/example/jeonsilog/fcm/services/FirebaseMessagingService.kt
Labels: fix

#135 [PR] develop <- ISSUE-73-fix/#129-FIX-Exhibition
  JeonsiLog/app/src/main/java/com/example/jeonsilog/base/BaseFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/api/ReviewApi.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/review/GetCheckReviewResponse.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/review/GetReviewsExhibitionResponse.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/review/PatchReviewRequest.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/review/ReviewRepository.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/review/ReviewRepositoryImpl.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/DialogWithIllus.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ExhibitionFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ExhibitionReviewRvAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/PosterFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/WritingReviewFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/viewmodel/ExhibitionViewModel.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/viewmodel/ExhibitionWritingViewModel.kt
  JeonsiLog/app/src/main/res/layout/fragment_writing_review.xml
  JeonsiLog/app/src/main/res/layout/item_exhibition_review.xml
  JeonsiLog/app/src/main/res/values/strings.xml
Labels: fix

#140 [PR] develop <- ISSUE-73-fix/#129-FIX-Exhibition
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ExhibitionFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ReviewFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/WritingReviewFragment.kt
  JeonsiLog/app/src/main/res/layout/fragment_exhibition.xml
Labels: fix

#142 [PR] develop <- ISSUE-77-mod/#141-MOD-DefalutProfile
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageFragment.kt
  JeonsiLog/app/src/main/res/layout/fragment_review.xml
  JeonsiLog/app/src/main/res/layout/item_review_reply.xml
Labels: mod

#144 [PR] develop <- ISSUE-73fix/#129-FIX-Exhibition
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/api/ReplyApi.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/reply/GetHasReplyResponse.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/reply/ReplyRepository.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/reply/ReplyRepositoryImpl.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/MainActivity.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ExhibitionFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ExhibitionReplyRvAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ReviewFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/notification/NotificationRvAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/viewmodel/ExhibitionViewModel.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/widget/utils/GlobalApplication.kt
  JeonsiLog/app/src/main/res/layout/activity_login.xml
  JeonsiLog/app/src/main/res/layout/fragment_poster.xml
  JeonsiLog/app/src/main/res/layout/fragment_review.xml
  JeonsiLog/app/src/main/res/layout/fragment_signup.xml
  JeonsiLog/app/src/main/res/layout/fragment_tos.xml
  JeonsiLog/app/src/main/res/layout/fragment_writing_review.xml
  JeonsiLog/app/src/main/res/values/strings.xml
Labels: fix

#147 [PR] main <- develop
  JeonsiLog/app/build.gradle
Labels: release

#149 [PR] develop <- ISSUE-80-fix/#148-FIX-Proflie
  JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/review/GetReviewsResponse.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageReviewFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserReviewFragment.kt
  JeonsiLog/app/src/main/res/layout/item_my_page_review.xml
  JeonsiLog/app/src/main/res/layout/item_other_user_review.xml
Labels: fix

#152 [PR] develop <- ISSUE-81-fix/#151-FIX-PhotoCalendar
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/admin/AdminReviewFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/RecordSearchFragment.kt
Labels: fix

#155 [PR] develop <- ISSUE-82-fix/#154-FIX-Admin
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/admin/AdminExhibitionFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/admin/AdminReviewFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/admin/AdminSearchFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/admin/AdminSearchRvAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/home/HomeFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/home/HomeRvAdapter.kt
Labels: fix

#156 [PR] main <- develop
  JeonsiLog/app/build.gradle
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/admin/AdminExhibitionFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/admin/AdminReviewFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/admin/AdminSearchFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/admin/AdminSearchRvAdapter.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/home/HomeFragment.kt
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/home/HomeRvAdapter.kt
Labels: release

#157 [PR] main <- develop
  JeonsiLog/app/build.gradle
  JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ExhibitionFragment.kt
  JeonsiLog/app/src/main/res/layout/fragment_admin_exhibition.xml
  JeonsiLog/app/src/main/res/layout/fragment_exhibition.xml
  JeonsiLog/app/src/main/res/values/strings.xml
Labels: release
